module.exports = {
  "black": [
/* Original Deck */
    {"text": "_______?\nThere's an app\nfor that."},
    {"text": "What's that smell?"},
    {"text": "Why can't I sleep\nat night?"},
    {"text": "I got 99 problems\nbut _______ ain't\none."},
    {"text": "What's a girl's\nbest friend?"},
    {"text": "This is the way\nthe world ends -\nNot with a\nbang but with\n_______."},
    {"text": "What is Batman's\nguilty pleasure?"},
    {"text": "TSA guidelines\nnow prohibit\n_______\non airplanes."},
    {"text": "What ended my\nlast relationship?"},
    {"text": "MTV's new\nreality show\nfeatures eight\nwashed-up\ncelebrities\nliving with _______."},
    {"text": "I drink to forget\n_______."},
    {"text": "I'm sorry,\nProfessor, but\nI couldn't\ncomplete my\nhomework\nbecause of _______."},
    {"text": "Alternative\nmedicine is\nnow embracing\nthe curative\npowers of _______."},
    {"text": "What's that sound?"},
    {"text": "What's the next\nHappy Meal\u00AE toy?"},
    {"text": "It's a pity that\nkids these days\nare all getting\ninvolved with\n_______."},
    {"text": "In the new\nDisney Channel\nOriginal Movie,\nHannah Montana\nstruggles with\n_______ for the first\ntime."},
    {"text": "_______.\nThat's how I\nwant to die."},
    {"text": "What does Dick\nCheney prefer?"},
    {"text": "Instead of coal,\nSanta now gives\nthe bad children\n_______."},
    {"text": "Next from J.K.\nRowling: Harry\nPotter and the\nChamber of _______."},
    {"text": "A romantic,\ncandlelit dinner\nwould be\nincomplete\nwithout _______."},
    {"text": "White people like\n_______."},
    {"text": "_______.\nBetcha can't\nhave just one!"},
    {"text": "War!\nWhat is it good\nfor?"},
    {"text": "BILLY MAYS\nHERE FOR _______."},
    {"text": "_______.\nHigh five, bro."},
    {"text": "During sex,\nI like to think\nabout _______."},
    {"text": "What did I bring\nback from Mexico?"},
    {"text": "What are my\nparents hiding\nfrom me?"},
    {"text": "What will always\nget you laid?"},
    {"text": "What would\ngrandma find\ndisturbing, yet\noddly charming?"},
    {"text": "What did the\nU.S. airdrop to\nthe children of\nAfghanistan?"},
    {"text": "What helps\nObama unwind?"},
    {"text": "What's there a\nton of in heaven?"},
    {"text": "Major League\nBaseball has\nbanned _______ for\ngiving players\nan unfair\nadvantage."},
    {"text": "When I am a\nbillionaire, I\nshall erect a\n50-foot statue\nto commemorate\n_______."},
    {"text": "What's the new\nfad diet?"},
    {"text": "When I am the\nPresident of\nthe United\nStates, I will\ncreate the\nDepartment of\n_______."},
    {"text": "_______.\nIt's a trap!"},
    {"text": "How am I\nmaintaining my\nrelationship\nstatus?"},
    {"text": "What will I\nbring back in\ntime to convince\npeople that I\nam a powerful\nwizard?"},
    {"text": "While the\nUnited States\nraced the Soviet\nUnion to the\nmoon, the Mexican\ngovernment\nfunneled millions\nof pesos into\nresearch on _____."},
    {"text": "Coming to Broadway\nthis season,\n_____: The Musical."},
    {"text": "What's my\nsecret power?"},
    {"text": "What gives me\nuncontrollable\ngas?"},
    {"text": "But before I kill\nyou, Mr. Bond,\nI must show you\n_______."},
    {"text": "What never fails\nto liven up the\nparty?"},
    {"text": "What am I giving\nup for Lent?"},
    {"text": "What do old\npeople smell\nlike?"},
    {"text": "The class field\ntrip was\ncompletely\nruined by _______."},
    {"text": "When Pharaoh\nremained\nunmoved, Moses\ncalled down a\nplague of _______."},
    {"text": "I do not know\nwith which\nweapons World\nWar III will be\nfought, but\nWorld War IV will\nbe fought\nwith _______."},
    {"text": "What's Teach for\nAmerica using to\ninspire inner\ncity students\nto succeed?"},
    {"text": "In Michael\nJackson's final\nmoments, he\nthought about\n_______."},
    {"text": "Why do I hurt all\nover?"},
    {"text": "Studies show that\nlab rats navigate\nmazes 50% faster\nafter being\nexposed to _______."},
    {"text": "Why am I sticky?"},
    {"text": "What's my anti-drug?"},
    {"text": "And the Academy\nAward for _______\ngoes to _______.", "numResponses": 2},
    {"text": "For my next trick,\nI will pull\n_______ out of\n_______.", "numResponses": 2},
    {"text": "_______: Good to\nthe last drop."},
    {"text": "What did Vin\nDiesel eat for\ndinner?"},
    {"text": "_______: kid-tested,\nmother-approved."},
    {"text": "What gets better\nwith age?"},
    {"text": "I never truly\nunderstood\n_______ until I\nencountered\n_______.", "numResponses": 2},
    {"text": "Rumor has it\nthat Vladimir\nPutin's favorite\ndelicacy is _______\nstuffed with _______.", "numResponses": 2},
    {"text": "Lifetime\u00AE presents\n_______, the story\nof _______.", "numResponses": 2},
    // {"text": "Make a haiku.", "numResponses": 3, "numDraws": 2},
    {"text": "In M. Night\nShyamalan's\nnew movie, Bruce\nWillis discovers\nthat _______ had\nreally been _______\nall along.", "numResponses": 2},
    {"text": "_______ is a slippery\nslope that leads\nto _______.", "numResponses": 2},
    {"text": "In a world ravaged\nby _______,\nour only solace\nis _______.", "numResponses": 2},
    {"text": "That's right,\nI killed _______.\nHow, you ask?\n_______.", "numResponses": 2},
    {"text": "When I was\ntripping on acid,\n_______ turned\ninto _______.", "numResponses": 2},
    // {"text": "_______ + _______\n= _______.",  "numResponses": 3, "numDraws": 2},
    {"text": "What's the next\nsuperhero/sidekick\nduo?", "numResponses": 2},
    {"text": "Dear Abby,\nI'm having some\ntrouble with\n_______ and would\nlike your advice."},
    {"text": "After the\nearthquake, Sean\nPenn brought\n_______ to the people of\nHaiti."},
    {"text": "In L.A. County\nJail, word is\nyou can trade\n200 cigarettes\nfor _______."},
    {"text": "Maybe she's born\nwith it. Maybe\nit's _______."},
    {"text": "Life for\nAmerican Indians\nwas forever\nchanged when the\nWhite Man\nintroduced them\nto _______."},
    {"text": "Next on ESPN2,\nthe World Series\nof _______."},
    {"text": "Step 1: _______.\nStep 2: _______.\nStep 3: Profit.", "numResponses": 2},
    {"text": "Here is the church\nHere is the steeple\nOpen the doors\nAnd there is _____."},
    {"text": "How did I lose\nmy virginity?"},
    {"text": "During his\nchildhood,\nSalvador Dali\nproduced\nhundreds of\npaintings of _____."},
    {"text": "In 1,000 years,\nwhen paper money\nis a distant\nmemory, how will\nwe pay for goods\nand services?"},
    {"text": "What don't you\nwant to find in\nyour Kung Pao\nchicken?"},
    {"text": "The Smithsonian\nMuseum of\nNatural History\nhas just opened\nan exhibit on\n_______."},
    {"text": "Daddy, why is\nMommy crying?"},
/* 2020 Deck */
    {"text": "I can't sleep at night\nwithout _____ ."},
    {"text": "*CzerName* loves _____ ."},
    {"text": "*CzarName* is oddly\nturned on by _____ ."},
    {"text": "My last relationship was\nruined by _____ ."},
    {"text": "Comic Con was ruined\nwhen _____ showed up..."},
    {"text": "*CzarName* is always\n_____ ."},
    {"text": "How do you get a women\nin bed? _____"},
    {"text": "There's no such thing as\n_____ ."},
    {"text": "GOD HATES _____ !!"},
    {"text": "_____ : The solution\nfor women."},
    {"text": "Bros before _____ ."},
    {"text": "Thanks to YouTube I have\nan unrealistic\nexpectation of _____ ."},
    {"text": "The party was really\nmade awkward when they\nstarted _____ ..."},
    {"text": "The sex was great until\nthey started _____ ."},
    {"text": "My gamer tag is _____ ."},
    {"text": "Don't threaten me with\n_____ . It'll only turn\nme on..."},
    {"text": "A mother was called into\nher daughter's school\nwhen they discovered she\nwas talking to _____ ."},
    {"text": "I can't believe my mum\nfound pornhub.com/ _____\nin my search history..."},
    {"text": "A mother was called into\nher daughter's school\nwhen they discovered she\nwas doing _____ online."},
    {"text": "Excessive drinking + a\nlack of self control =\n_____ ."},
    {"text": "Candy doesn't work\nanymore, nowadays kids\nwill see _____ and hop\nin a van!"},
    {"text": "Girls don't love boys!\nThey love _____ !"},
    {"text": "I can't believe _____\nturned out to be\nracist..."},
    {"text": "TRIGGER WARNING\n_____!!!"},
    {"text": "Don't post about _____\nit's my trigger..."},
    {"text": "_____ the rich!"},
    {"text": "HELP WANTED!!Need\nassistance with _____!\nNo experience necessary!"},
    {"text": "_____ was totally worth\nthe trauma."},
    {"text": "What ruined my first\nkiss? _____"},
    {"text": "What never fails to\nlighten up a party?\n_____"},
    {"text": "_____ ! It's a trap!!"},
    {"text": "No, no no no NO! I will\nnot let _____ ruin the\nwedding!!"},
    {"text": "To me, happiness is\n_____ ."},
    {"text": "I follow a strict plan.\nFirst date:\nDinner. Second date:\nKiss. Third date: _____ ."},
    {"text": "What will never get you\nlaid? _____"},
    {"text": "What will always get you\nlaid? _____"},
    {"text": "The discovery channel\nnow presents: _____\nweek!"},
    {"text": "Make _____ great again!!"},
    {"text": "When I'm president I\nwill be enforcing _____\nas a law!"},
    {"text": "I will do anything to\nfuck _____ ."},
    {"text": "What was Michael\nJackson's last thoughts\nbefore he died? _____"},
    {"text": "If Michael Jackson's\nwalls could speak, they\nwould tell the story of\n_____ ."},
    {"text": "Fine, I despise _____ .\nThere I said it."},
    {"text": "TSA guidelines now\nprohibit _____ on\nairlines."},
    {"text": "I drink to forget _____\n."},
    {"text": "Science cannot explain\n_____ ."},
    {"text": "The military now give\nout medals for _____ !"},
    {"text": "BUZZFEED's newest\narticle is all about\n_____ ."},
    {"text": "\"Baby.. what's wrong?\"\n_____"},
    {"text": "No really! I'm allergic\nto _____ !"},
    {"text": "During puberty, you may\ndevelop an interest in\n_____ , don't worry,\nthis is normal."},
    {"text": "I hate to say it but...\n_____ is pretty gay."},
    {"text": "What's the key to a\nlasting marriage? _____"},
    {"text": "Can't it wait? I'm in\nthe middle of _____ ."},
    {"text": "I would describe myself\nas _____ ."},
    {"text": "The best thing about\nbeing a man is _____ ."},
    {"text": "The worst thing about\nbeing a man is _____ ."},
    {"text": "The best thing about\nbeing a woman is _____ ."},
    {"text": "The worst thing about\nbeing a woman is _____ ."},
    {"text": "# _____ !!"},
    {"text": "# _____ IsOverParty!!!"},
    {"text": "Anti-vaxxers are now\nsaying _____ causes\nautism."},
    {"text": "What's worse than the\nholocaust?  _____"},
    {"text": "Best idea for\nentertaining kids on a\nrainy day? _____"},
    {"text": "I thought 2020 was as\nbad as it was gonna get,\nthen _____ happened."},
    {"text": "*CzarName* is the CEO of\n_____ ."},
    {"text": "What is the meaning of\nlife? _____"},
    {"text": "_____ ? That doesn't\nexist."},
    {"text": "If I see another white\ngirl self diagnosing\nherself with _____ I'm\ngonna scream!"},
    {"text": "_____ ? Of course it's\nok, in fact, I encourage\nit."},
    {"text": "_____ is how I lost my\nvirginity."},
    {"text": "The perfect date would\nend with _____ ."},
    {"text": "_____ got me out of\nhaving sex with them."},
    {"text": "_____ will cause riots."},
/* Official Australia Deck */
    {"text": "The Great Barrier Reef\nis under dire threat\nfrom overfishing, toxic\nrunoff, and _____ ."},
    {"text": "The most memorable image\nfrom this year's Sydney\nMardi Gras was _____ on\na float."},
    {"text": "Australia: where even\n_____ can kill you."},
    {"text": "Channel 9 is pleased to\npresent its new variety\nshow, \"Hey Hey It's\n_____ \","},
    {"text": "How is Tony Abbott\nstopping the boats?\n_____ ."},
    {"text": "In Australia, _____ is\ntwice as big and twice\nas deadly."},
    {"text": "Crikey! I've never seen\n_____ like this! Let's\nget a bit closer."},
    {"text": "Oi! Show us _____ !"},
    {"text": "Well may we say \"God\nsave the Queen\", because\nnothing will save _____\n."},
    {"text": "What broke up the\noriginal Wiggles? _____\n."},
    {"text": "I waited six months at\nthe Christmas Island\nImmigration Detention\nCentre and all I got was\n_____ ."},
    {"text": "Come to Melbourne, where\nyou can relax in our\nworld-famous spas,\nexperience the\nnightlife, or simply\nenjoy _____ by the\npoolside."},
    {"text": "This year, Australia's\nparliament will\nofficially apologize to\nthe Aboriginal\npopulation for _____ ."},
    {"text": "What should harden the\nfuck up? _____ ."},
    {"text": "I love a sunburnt\ncountry; a land of\nsweeping plains, of\nragged mountain ranges,\nof _____ ."},
    {"text": "Australians all let us\nrejoice, For we are\nyoung and _____ ."},
    {"text": "Good work, Mr Squiggle!\nIt looks just like _____\n."},
    {"text": "Clive Palmer's new theme\npark puts _____ on\ndisplay for all to see."},
    {"text": "Australians have voted\nto replace the Union\nJack with an image of\n_____ on the national\nflag."},
    {"text": "Nesquik® makes _____\nfun!"},
    {"text": "The new Scienceworks\nexhibition gives kids a\nrare look inside of\n_____ ."},
    {"text": "Are you thinking what\nI'm thinking B1? I think\nI am B2: It's _____\ntime."},
/* By Assholes, For Assholes Deck */
    {"text": "Cookie Monster switched\nto cookies after a\ncrippling addiction to\n_____ ."},
    {"text": "I am ashamed to admit\nthat I've traded sexual\nfavors for _____ ."},
    {"text": "It's so hard finding\n_____ porn, I usually\nhave to settle for _____\n.", "numResponses": 2},
    {"text": "The road to Hell is\npaved with _____ ."},
    {"text": "I once did porn, until\n_____ ."},
    {"text": "Now that Joe Biden\nis out of office he has\nmore time to spend\nfollowing his true\npasssion, _____ ."},
    {"text": "The name of my sex tape\nis _____ ."},
    {"text": "After years of training,\nI'm finally a master of\n_____ ."},
    {"text": "After a few hours on the\ndeep web, I found an\nentire website dedicated\nto _____ ."},
    {"text": "Is it wrong that I want\nto fuck _____ ?"},
    {"text": "That horrible feeling\nwhen you accidentally\nshow your _____ porn\nfolder live on Twitch."},
    {"text": "_____ always makes me\ncum."},
    {"text": "WTF, I didn't need to\nknow you did _____ with\nyour girlfriend!"},
    {"text": "The sex ed teacher got\nfired for using _____ in\nhis class."},
    {"text": "The newest advancement\nin sex toy technology is\n_____ ."},
    {"text": "I ain't saying she's a\ngold digger, but she\nain't messing with _____\n."},
    {"text": "The date was going\nreally well, until she\nstarted talking about\n_____ ."},
    {"text": "People need to stop\ntalking about _____ ."},
    {"text": "_____ was fun, but then\nshe woke up."},
    {"text": "Our Father, who art in\nheaven, _____ be thy\nname."},
    {"text": "We need to prioritize\nscientific research on\n_____ ."},
    {"text": "Breaking News: _____ to\nbe entered as evidence\nin the Trump impeachment\ncase."},
    {"text": "Donald plans to build a\nwall to keep the _____\nout."},
    {"text": "Wanna see me _____ ?\nWanna see me do it\nagain?"},
    {"text": "Make America _____\nAgain!"},
    {"text": "When I walked into a KKK\nmeeting, I saw _____ ."},
    {"text": "My favorite pickup line:\n_____ ."},
    {"text": "_____ ... not again."},
    {"text": "What would you do for a\nKlondike Bar? _____"},
    {"text": "What is Reddit\noverreacting about now?\n_____"},
    {"text": "I thought my job sucked,\nbut then I found out\nabout _____ ."},
    {"text": "This isn't a hickey,\nit's just _____ ."},
    {"text": "The _____ card is the\nreason I don't play this\ngame with my parents."},
    {"text": "Whitey's gotta pay, and\nthe payment is _____ ."},
    {"text": "In their next game, Game\nFreak is creating a new\nPokemon based off of\n_____ ."},
    {"text": "I think there's  _____\nin my Happy Meal."},
    {"text": "Losing my virginity was\nmore satisfying than\n_____ ."},
    {"text": "Don't worry officer,\nthat's just my _____ ."},
    {"text": "More restaurants need\n_____ on the menu."},
    {"text": "_____ isn't illegal,\nright?"},
    {"text": "_____ is gay."},
    {"text": "_____ ... what a\nshameful display."},
    {"text": "My college roommate has\na weird obsession with\n_____ ."},
    {"text": "I snuck into the White\nHouse and I saw _____ ."},
    {"text": "_____ , hot."},
    {"text": "The latest reality\nseries on the History\nChannel features two\nfriends that have made a\nfortune selling _____ ."},
    {"text": "That awkward moment when\nyou realize _____ is\nillegal."},
    {"text": "I would be on board with\nScientology if it\nweren't for _____ ."},
    {"text": "Pfft, _____ isn't a big\ndeal."},
    {"text": "I hope Rule 34 doesn't\napply to _____ ."},
    {"text": "With great power comes\n_____ ."},
    {"text": "Donald Trump's personal\nspank bank is full of\n_____ ."},
    {"text": "The FDA just recalled\nGerber baby formula for\nhaving _____ in it."},
    {"text": "Subscribe to my YouTube\nChannel for more _____ !"},
    {"text": "I never thought I'd say\nthis, but you really\nneed to try _____ ."},
    {"text": "In the shower, I think\nabout _____ ."},
    {"text": "Kim Jong Un has spent\nmillions of his people's\nmoney to fund his\naddiction to _____ ."},
    {"text": "Yesterday I found _____\nfor sale on eBay."},
    {"text": "What's in the briefcase?\n_____"},
    {"text": "I built my fort in _____\n."},
    {"text": "On the day set aside for\nthe Lord I like to _____\n."},
    {"text": "4 out of 5 dentists\nrecommend _____ ."},
    {"text": "It should be a goal of\nthe human race to ensure\nthat _____ never\nhappens."},
    {"text": "Donald Trump promised\n_____ as soon as he\nentered office."},
    {"text": "What did the blind\norphan boy get for\nChristmas? _____"},
    {"text": "Mommy, I think I'm _____\n."},
    {"text": "_____ is the best lube."},
    {"text": "Hello, this is my first\nmeeting and I'm addicted\nto _____ ."},
    {"text": "A new bill just passed\nthe U.S. Senate to\nlegalize _____ ."},
    {"text": "_____ always makes me\nflaccid."},
    {"text": "I always felt like Trump\nwould get impeached, but\nI never thought it would\nbe for _____ ."},
    {"text": "I found _____ under my\nbed."},
    {"text": "On a scale from _____\nto _____ how bad is your\npain?", "numResponses": 2},
    {"text": "My tummy was making the\nrumblies that only _____\ncould satisfy."},
    {"text": "I spent 8 hours straight\nedging to _____ ."},
    {"text": "Kids are playing a new\nVR game that lets them\nlive a day in the life\nof _____ ."},
    {"text": "I was surprised to see\n_____ in Hillary's\nemails."},
    {"text": "Death by _____ ."},
    {"text": "When I went fishing, I\ncaught _____ ."},
    {"text": "The secret 11th\nCommandment is _____ ."},
    {"text": "_____ is considered a\ndelicacy in North Korea."},
    {"text": "I'm so ashamed of _____\n."},
    {"text": "The children sprung from\nbed and ran down the\nstairs to find  _____\nunder the Christmas\ntree."},
    {"text": "reddit.com/r/ _____"},
    {"text": "KIDS REACT TO : \" _____\n\"."},
    {"text": "Donald Trump added _____\nto the White House."},
    {"text": "As long as we have _____\n, life is worth living."},
    {"text": "This workplace has been\n0 days without _____ ."}
  ],
  
  "white": [
/* Original Deck */
    {"text": "Coat hanger\nabortions."},
    {"text": "Man meat."},
    {"text": "Autocannibalism."},
    {"text": "Vigorous jazz\nhands."},
    {"text": "Flightless birds."},
    {"text": "Pictures of boobs."},
    {"text": "Doing the right\nthing."},
    {"text": "The violation of our\nmost basic human\nrights."},
    {"text": "Viagra\u00AE."},
    {"text": "Self-loathing."},
    {"text": "Spectacular abs."},
    {"text": "A balanced\nbreakfast."},
    {"text": "Roofies."},
    {"text": "Concealing a\nboner."},
    {"text": "Amputees."},
    {"text": "The Big Bang."},
    {"text": "Former President\nGeorge W. Bush."},
    {"text": "The Rev. Dr.\nMartin Luther\nKing, Jr."},
    {"text": "Smegma."},
    {"text": "Being marginalized."},
    {"text": "Cuddling."},
    {"text": "Laying an egg."},
    {"text": "The Pope."},
    {"text": "Aaron Burr."},
    {"text": "Genital piercings."},
    {"text": "Fingering."},
    {"text": "A bleached asshole."},
    {"text": "Horse meat."},
    {"text": "Fear itself."},
    {"text": "Science."},
    {"text": "Elderly Japanese\nmen."},
    {"text": "Stranger danger."},
    {"text": "The terrorists."},
    {"text": "Praying the gay\naway."},
    {"text": "Same-sex ice\ndancing."},
    {"text": "Ethnic cleansing."},
    {"text": "Cheating in the\nSpecial Olympics."},
    {"text": "German dungeon\nporn."},
    {"text": "Bingeing and\npurging."},
    {"text": "Making a pouty face."},
    {"text": "William Shatner."},
    {"text": "Heteronormativity."},
    {"text": "Nickelback."},
    {"text": "Tom Cruise."},
    {"text": "The profoundly\nhandicapped."},
    {"text": "The placenta."},
    {"text": "Chainsaws for\nhands."},
    {"text": "Arnold\nSchwarzenegger."},
    {"text": "An icepick lobotomy."},
    {"text": "Goblins."},
    {"text": "Object\npermanence."},
    {"text": "Dying."},
    {"text": "Foreskin."},
    {"text": "A falcon with a cap\non its head."},
    {"text": "Hormone injections."},
    {"text": "Dying of dysentery."},
    {"text": "Sexy pillow fights."},
    {"text": "The invisible hand."},
    {"text": "A really cool hat."},
    {"text": "Sean Penn."},
    {"text": "Heartwarming\norphans."},
    {"text": "The clitoris."},
    {"text": "The Three-Fifths\ncompromise."},
    {"text": "A sad handjob."},
    {"text": "Men."},
    {"text": "Historically black\ncolleges."},
    {"text": "A micropenis."},
    {"text": "Raptor attacks."},
    {"text": "Agriculture."},
    {"text": "Vikings."},
    {"text": "Pretending to care."},
    {"text": "The Underground\nRailroad."},
    {"text": "My humps."},
    {"text": "Being a dick to\nchildren."},
    {"text": "Geese."},
    {"text": "Bling."},
    {"text": "Sniffing glue."},
    {"text": "The South."},
    {"text": "An Oedipus\ncomplex."},
    {"text": "Eating all of\nthe cookies\nbefore the AIDS\nbake-sale."},
    {"text": "Sexting."},
    {"text": "YOU MUST\nCONSTRUCT\nADDITIONAL\nPYLONS."},
    {"text": "Mutually-assured\ndestruction."},
    {"text": "Sunshine and\nrainbows."},
    {"text": "Count Chocula."},
    {"text": "Sharing needles."},
    {"text": "Being rich."},
    {"text": "Skeletor."},
    {"text": "A sausage festival."},
    {"text": "Michael Jackson."},
    {"text": "Emotions."},
    {"text": "Farting and\nwalking away."},
    {"text": "The Chinese\ngymnastics team."},
    {"text": "Necrophilia."},
    {"text": "Spontaneous\nhuman combustion."},
    {"text": "Yeast."},
    {"text": "Leaving an awkward\nvoicemail."},
    {"text": "Dick Cheney."},
    {"text": "White people."},
    {"text": "Penis envy."},
    {"text": "Teaching a robot\nto love."},
    {"text": "Sperm whales."},
    {"text": "Scrubbing under\nthe folds."},
    {"text": "Panda sex."},
    {"text": "Whipping it out."},
    {"text": "Catapults."},
    {"text": "Masturbation."},
    {"text": "Natural selection."},
    {"text": "Opposable\nthumbs."},
    {"text": "A sassy black\nwoman."},
    {"text": "AIDS."},
    {"text": "The KKK."},
    {"text": "Figgy pudding."},
    {"text": "Seppuku."},
    {"text": "Gandhi."},
    {"text": "Preteens."},
    {"text": "Toni Morrison's\nvagina."},
    {"text": "Five-Dollar\nFootlongs\u2122."},
    {"text": "Land mines."},
    {"text": "A sea of troubles."},
    {"text": "A zesty breakfast\nburrito."},
    {"text": "Christopher\nWalken."},
    {"text": "Friction."},
    {"text": "Balls."},
    {"text": "Dental dams."},
    {"text": "A can of whoop-ass."},
    {"text": "A tiny horse."},
    {"text": "Waiting 'til\nmarriage."},
    {"text": "Authentic\nMexican cuisine."},
    {"text": "Genghis Khan."},
    {"text": "Old-people smell."},
    {"text": "Feeding Rosie\nO'Donnell."},
    {"text": "Pixelated bukkake."},
    {"text": "Friends with\nbenefits."},
    {"text": "The token minority."},
    {"text": "The Tempur-Pedic\u00AE\nSwedish Sleep\nSystem\u2122."},
    {"text": "A thermonuclear\ndetonation."},
    {"text": "Take-backsies."},
    {"text": "The Rapture."},
    {"text": "A cooler full of\norgans."},
    {"text": "Sweet, sweet\nvengeance."},
    {"text": "RoboCop."},
    {"text": "Keanu Reeves."},
    {"text": "Drinking alone."},
    {"text": "Giving 110%."},
    {"text": "Flesh-eating\nbacteria."},
    {"text": "The American\nDream."},
    {"text": "Taking off your\nshirt."},
    {"text": "Me time."},
    {"text": "A murder most foul."},
    {"text": "The inevitable heat\ndeath of the\nuniverse."},
    {"text": "The folly of man."},
    {"text": "That thing that\nelectrocutes your\nabs."},
    {"text": "Holograms\nAgainst\nHumanity."},
    {"text": "Fiery poops."},
    {"text": "Poor people."},
    {"text": "Edible underpants."},
    {"text": "Britney Spears\nat 55."},
    {"text": "All-you-can-eat\nshrimp for $4.99."},
    {"text": "Pooping back and\nforth. Forever."},
    {"text": "Fancy Feast\u00AE."},
    {"text": "Jewish fraternities."},
    {"text": "Being a\nmotherfucking\nsorcerer."},
    {"text": "Pulling out."},
    {"text": "Picking up girls at\nthe abortion clinic."},
    {"text": "The homosexual\nagenda."},
    {"text": "The Holy Bible."},
    {"text": "Passive-aggression."},
    {"text": "Ronald Reagan."},
    {"text": "Vehicular\nmanslaughter."},
    {"text": "Nipple blades."},
    {"text": "Assless chaps."},
    {"text": "Full frontal nudity."},
    {"text": "Hulk Hogan."},
    {"text": "Daddy issues."},
    {"text": "The hardworking\nMexican."},
    {"text": "Natalie Portman."},
    {"text": "Waking up\nhalf-naked in a\nDenny's parking\nlot."},
    {"text": "God."},
    {"text": "Sean Connery."},
    {"text": "Saxophone solos."},
    {"text": "Gloryholes."},
    {"text": "The World of\nWarcraft."},
    {"text": "Homeless people."},
    {"text": "Scalping."},
    {"text": "Darth Vader."},
    {"text": "Eating the last\nknown bison."},
    {"text": "Guys who don't\ncall."},
    {"text": "Hot Pockets\u00AE."},
    {"text": "A time travel\nparadox."},
    {"text": "The milk man."},
    {"text": "Testicular torsion."},
    {"text": "Dropping a\nchandelier on\nyour enemies\nand riding the\nrope up."},
    {"text": "World peace."},
    {"text": "A salty surprise."},
    {"text": "Poorly-timed\nHolocaust jokes."},
    {"text": "Smallpox blankets."},
    {"text": "Licking things to\nclaim them as your\nown."},
    {"text": "The heart of a child."},
    {"text": "Robert Downey, Jr."},
    {"text": "Lockjaw."},
    {"text": "Eugenics."},
    {"text": "A good sniff."},
    {"text": "Friendly fire."},
    {"text": "The taint;\nthe grundle;\nthe fleshy\nfun-bridge."},
    {"text": "Wearing underwear\ninside-out to avoid\ndoing laundry."},
    {"text": "Hurricane Katrina."},
    {"text": "Free samples."},
    {"text": "Jerking off into a\npool of children's\ntears."},
    {"text": "A foul mouth."},
    {"text": "The glass ceiling."},
    {"text": "Republicans."},
    {"text": "Explosions."},
    {"text": "Michelle Obama's\narms."},
    {"text": "Getting really high."},
    {"text": "Attitude."},
    {"text": "Sarah Palin."},
    {"text": "The \u00FCbermensch."},
    {"text": "Altar boys."},
    {"text": "My soul."},
    {"text": "My sex life."},
    {"text": "72 virgins."},
    {"text": "Pabst Blue Ribbon."},
    {"text": "Domino's\u2122 Oreo\u2122\nDessert Pizza."},
    {"text": "A snapping turtle\nbiting the tip of\nyour penis."},
    {"text": "Half-assed foreplay."},
    {"text": "My collection of\nhigh-tech sex toys."},
    {"text": "A middle-aged man\non roller skates."},
    {"text": "Bitches."},
    {"text": "Bill Nye the Science\nGuy."},
    {"text": "A windmill full of\ncorpses."},
    {"text": "Adderall\u2122."},
    {"text": "A stray pube."},
    {"text": "Prancing."},
    {"text": "Passing a kidney\nstone."},
    {"text": "A brain tumor."},
    {"text": "Leprosy."},
    {"text": "Puppies!"},
    {"text": "Bees?"},
    {"text": "Frolicking."},
    {"text": "Repression."},
    {"text": "Road head."},
    {"text": "A bag of magic\nbeans."},
    {"text": "An asymmetric\nboob job."},
    {"text": "Dead parents."},
    {"text": "A mating display."},
    {"text": "A mime having a\nstroke."},
    {"text": "Stephen Hawking\ntalking dirty."},
    {"text": "African children."},
    {"text": "Mouth herpes."},
    {"text": "Overcompensation."},
    {"text": "Riding off into\nthe sunset."},
    {"text": "Being on fire."},
    {"text": "Tangled Slinkys."},
    {"text": "Civilian casualties."},
    {"text": "Auschwitz."},
    {"text": "Not reciprocating\noral sex."},
    {"text": "Lactation."},
    {"text": "Being fabulous."},
    {"text": "Shaquille O'Neal's\nacting career."},
    {"text": "My relationship\nstatus."},
    {"text": "Asians who aren't\ngood at math."},
    {"text": "Alcoholism."},
    {"text": "Incest."},
    {"text": "Grave robbing."},
    {"text": "Hope."},
    {"text": "8 oz. of sweet\nMexican black-tar\nheroin."},
    {"text": "Kids with ass\ncancer."},
    {"text": "Winking at old\npeople."},
    {"text": "The Jews."},
    {"text": "Justin Bieber."},
    {"text": "Doin' it in the butt."},
    {"text": "The Hamburglar."},
    {"text": "Swooping."},
    {"text": "Classist\nundertones."},
    {"text": "New Age music."},
    {"text": "Not giving a shit\nabout the Third\nWorld."},
    {"text": "A hot mess."},
    {"text": "Tentacle porn."},
    {"text": "Lumberjack\nfantasies."},
    {"text": "Scientology."},
    {"text": "Estrogen."},
    {"text": "Judge Judy."},
    {"text": "Dick fingers."},
    {"text": "Surprise sex!"},
    {"text": "Police brutality."},
    {"text": "Passable\ntransvestites."},
    {"text": "When you fart and a\nlittle bit comes out."},
    {"text": "Oompa-Loompas."},
    {"text": "Obesity."},
    {"text": "Tasteful sideboob."},
    {"text": "Hot people."},
    {"text": "BATMAN!!!"},
    {"text": "Black people."},
    {"text": "A gassy antelope."},
    {"text": "Sexual tension."},
    {"text": "Racially-biased\nSAT questions."},
    {"text": "Porn stars."},
    {"text": "Muhammed\n(Praise Be Unto Him)."},
    {"text": "Puberty."},
    {"text": "A disappointing\nbirthday party."},
    {"text": "An erection that\nlasts longer than\nfour hours."},
    {"text": "Getting so angry\nthat you pop a\nboner."},
    {"text": "Wifely duties."},
    {"text": "Two midgets\nshitting into a\nbucket."},
    {"text": "Queefing."},
    {"text": "Golden showers."},
    {"text": "Barack Obama."},
    {"text": "A robust mongoloid."},
    {"text": "An M. Night\nShyamalan plot\ntwist."},
    {"text": "Getting drunk on\nmouthwash."},
    {"text": "Lunchables\u2122."},
    {"text": "Women in yogurt\ncommercials."},
    {"text": "John Wilkes Booth."},
    {"text": "Powerful thighs."},
    {"text": "Multiple stab\nwounds."},
    {"text": "Cybernetic\nenhancements."},
    {"text": "Serfdom."},
    {"text": "Kanye West."},
    {"text": "Women's suffrage."},
    {"text": "Children on\nleashes."},
    {"text": "Harry Potter erotica."},
    {"text": "The Dance of the\nSugar Plum Fairy."},
    {"text": "Lance Armstrong's\nmissing testicle."},
    {"text": "Parting the Red Sea."},
    {"text": "The Amish."},
    {"text": "Dead babies."},
    {"text": "Child beauty\npageants."},
    {"text": "AXE Body Spray."},
    {"text": "Centaurs."},
    {"text": "Copping a feel."},
    {"text": "Grandma."},
    {"text": "Famine."},
    {"text": "The Trail of Tears."},
    {"text": "The miracle of\nchildbirth."},
    {"text": "Finger painting."},
    {"text": "A monkey smoking\na cigar."},
    {"text": "The Make-A-Wish\u00AE\nFoundation."},
    {"text": "Anal beads."},
    {"text": "The Force."},
    {"text": "Kamikaze pilots."},
    {"text": "Dry heaving."},
    {"text": "Active listening."},
    {"text": "Ghosts."},
    {"text": "The Hustle."},
    {"text": "Peeing a little bit."},
    {"text": "Another goddamn\nvampire movie."},
    {"text": "Shapeshifters."},
    {"text": "The Care Bear\nStare."},
    {"text": "Hot cheese."},
    {"text": "A defective condom."},
    {"text": "Teenage pregnancy."},
    {"text": "A Bop It\u2122."},
    {"text": "Expecting a burp\nand vomiting on\nthe floor."},
    {"text": "Horrifying laser\nhair removal\naccidents."},
    {"text": "Boogers."},
    {"text": "Unfathomable\nstupidity."},
    {"text": "Soup that is too hot."},
    {"text": "Morgan Freeman's\nvoice."},
    {"text": "Getting naked\nand watching\nNickelodeon."},
    {"text": "MechaHitler."},
    {"text": "Flying sex snakes."},
    {"text": "The true meaning\nof Christmas."},
    {"text": "My inner demons."},
    {"text": "Pac-Man\nuncontrollably\nguzzling cum."},
    {"text": "My vagina."},
    {"text": "A homoerotic\nvolleyball montage."},
    {"text": "Actually taking\ncandy from a baby."},
    {"text": "Crystal meth."},
    {"text": "Exactly what you'd\nexpect."},
    {"text": "Natural male\nenhancement."},
    {"text": "Passive-Aggressive\nPost-it notes."},
    {"text": "Inappropriate\nyodeling."},
    {"text": "Lady Gaga."},
    {"text": "The Little Engine\nThat Could."},
    {"text": "Vigilante justice."},
    {"text": "A death ray."},
    {"text": "Poor life choices."},
    {"text": "A gentle caress\nof the inner thigh."},
    {"text": "Embryonic stem\ncells."},
    {"text": "Nicolas Cage."},
    {"text": "Firing a rifle into\nthe air while balls\ndeep in a\nsquealing hog."},
    {"text": "Switching to\nGeico\u00AE."},
    {"text": "Erectile\ndysfunction."},
    {"text": "Home video of\nOprah sobbing into\na Lean Cuisine\u00AE."},
    {"text": "A bucket of fish\nheads."},
    {"text": "50,000 volts\nstraight to the\nnipples."},
    {"text": "Being fat and\nstupid."},
    {"text": "Hospice care."},
    {"text": "A pyramid of\nsevered heads."},
    {"text": "Getting married,\nhaving a few kids,\nbuying some stuff,\nretiring to Florida,\nand dying."},
    {"text": "A subscription to\nMen's Fitness."},
    {"text": "Crucifixion."},
    {"text": "A micropig wearing\na tiny raincoat and\nbooties."},
    {"text": "Some god-damn\npeace and quiet."},
    {"text": "Used panties."},
    {"text": "A tribe of warrior\nwomen."},
    {"text": "The penny whistle\nsolo from \"My Heart\nWill Go On\"."},
    {"text": "An oversized\nlollipop."},
    {"text": "Helplessly giggling\nat the mention of\nHutus & Tutsis."},
    {"text": "Not wearing pants."},
    {"text": "Consensual sex."},
    {"text": "Her Majesty,\nQueen Elizabeth II."},
    {"text": "Funky fresh rhymes."},
    {"text": "The art of seduction."},
    {"text": "The Devil himself."},
    {"text": "Advice from a wise,\nold black man."},
    {"text": "Destroying the\nevidence."},
    {"text": "The light of a billion\nsuns."},
    {"text": "Wet dreams."},
    {"text": "Synergistic\nmanagement\nsolutions."},
    {"text": "Growing a pair."},
    {"text": "Silence."},
    {"text": "An M16 assault\nrifle."},
    {"text": "Poopy diapers."},
    {"text": "A live studio\naudience."},
    {"text": "The Great\nDepression."},
    {"text": "A spastic nerd."},
    {"text": "Rush Limbaugh's\nsoft, shitty body."},
    {"text": "Stalin."},
    {"text": "Brown people."},
    {"text": "Rehab."},
    {"text": "Capturing Newt\nGingrich and\nforcing him to\ndance in a monkey\nsuit."},
    {"text": "Battlefield\namputations."},
    {"text": "An uppercut."},
    {"text": "Shiny objects."},
    {"text": "An ugly face."},
    {"text": "Menstrual rage."},
    {"text": "A bitch slap."},
    {"text": "One trillion dollars."},
    {"text": "Chunks of dead\nprostitute."},
    {"text": "The entire Mormon\nTabernacle Choir."},
    {"text": "The female orgasm."},
    {"text": "Extremely tight\npants."},
    {"text": "The Boy Scouts of\nAmerica."},
    {"text": "Stormtroopers."},
    {"text": "Throwing a virgin\ninto a volcano."},
/* 2020 Deck */
    {"text": "Dyslexia"},
    {"text": "Scoliosis"},
    {"text": "Changing your gender"},
    {"text": "Insomnia"},
    {"text": "Children"},
    {"text": "Racially motivated\nassault"},
    {"text": "Only dating blacks"},
    {"text": "Dykes"},
    {"text": "Skinny white boys"},
    {"text": "Black girls"},
    {"text": "Asian girls"},
    {"text": "Anime boys"},
    {"text": "Anime girls"},
    {"text": "Anime body pillows"},
    {"text": "Luscious, curvaceous,\ngorilla glue pussy."},
    {"text": "Pussy"},
    {"text": "Huge testicals"},
    {"text": "Never talking to your\nfather again"},
    {"text": "The capitalist pig Tom\nNook"},
    {"text": "Simps"},
    {"text": "Simping"},
    {"text": "Onlyfans"},
    {"text": "Incels"},
    {"text": "Neckbeards"},
    {"text": "3 inches of raw power!"},
    {"text": "Clout chasers"},
    {"text": "Rioting for an\nirrelevant cause"},
    {"text": "Gay for a day"},
    {"text": "Age Regression Therapy"},
    {"text": "English boys"},
    {"text": "American boys"},
    {"text": "Beating the shit out of\na homeless man for £1"},
    {"text": "Reading Donald Trump's\ntweets"},
    {"text": "Screaming your/their\nex's name"},
    {"text": "Playing ACNH"},
    {"text": "Twitch streaming"},
    {"text": "Twitch thots"},
    {"text": "VirginSlayer69"},
    {"text": "BigCocks420"},
    {"text": "CraigSmith87"},
    {"text": "Wolf-whistling at girl\nscouts"},
    {"text": "M-preg"},
    {"text": "Roleplaying as a toddler"},
    {"text": "Bussy"},
    {"text": "Tiktok mafia bosses"},
    {"text": "Tiktok POVs"},
    {"text": "A good time"},
    {"text": "Twinks"},
    {"text": "The hot substitute\nteacher"},
    {"text": "White gays"},
    {"text": "ACAB: assigned cowboy at\nbirth"},
    {"text": "The FEDS"},
    {"text": "A recently douched\nasshole"},
    {"text": "Yaoi"},
    {"text": "Hentai"},
    {"text": "Yuri"},
    {"text": "Isabelle from ACNH"},
    {"text": "Tom Nook"},
    {"text": "Timmy and Tommy"},
    {"text": "Blathers"},
    {"text": "Crazy Redd"},
    {"text": "Fuck(ing)"},
    {"text": "Eat(ing)"},
    {"text": "Vore(ing)"},
    {"text": "Furry sex"},
    {"text": "Fighting a woman for the\nlast spring roll at a\nChinese buffet"},
    {"text": "Reading NSFW Sonic the\nHedgehog fanfiction"},
    {"text": "Rolling a nat20"},
    {"text": "Rolling a crit fail"},
    {"text": "Anal sex"},
    {"text": "Fisting"},
    {"text": "First degree murder"},
    {"text": "Virginity"},
    {"text": "Being a virgin"},
    {"text": "Huge tits"},
    {"text": "Small tits"},
    {"text": "Being white"},
    {"text": "Being black"},
    {"text": "Being mixed race"},
    {"text": "Being asian"},
    {"text": "Ryan Reynolds"},
    {"text": "Furries"},
    {"text": "Sex Trafficking Ring"},
    {"text": "Ruined Childhoods"},
    {"text": "Losing my virginity"},
    {"text": "Vaguely consensual sex"},
    {"text": "Cosplaying"},
    {"text": "Being toxic"},
    {"text": "A porn star without\ndaddy issues"},
    {"text": "Erectile disfunction"},
    {"text": "Being a Karen"},
    {"text": "Worshipping that pussy"},
    {"text": "Years of oppression"},
    {"text": "Periods"},
    {"text": "Fuck all"},
    {"text": "A lifetime of\ninternalised guilt"},
    {"text": "Daddy issues"},
    {"text": "Mummy issues"},
    {"text": "MILFs"},
    {"text": "DILFs"},
    {"text": "Various STDs"},
    {"text": "E-girls"},
    {"text": "E-boys"},
    {"text": "A lack of talent,\nability, and any good\nquality in general."},
    {"text": "KAM2020"},
    {"text": "Being emotionally\nconstipated"},
    {"text": "White men"},
    {"text": "An AK-47"},
    {"text": "Kissing the homies\ngoodnight"},
    {"text": "Drunk-texting an ex"},
    {"text": "Tentacle porn"},
    {"text": "Incest"},
    {"text": "Finding out you're into\nincest"},
    {"text": "Essential oils"},
    {"text": "Anti-vaxxers"},
    {"text": "A gift wrapped anime\npillow"},
    {"text": "A 50/50 chance of\nfucking up every time"},
    {"text": "Ripping the condom"},
    {"text": "Pre-marital sex"},
    {"text": "Thicc from the back,\nclapped in the front"},
    {"text": "A beautiful shade of\nwhore"},
    {"text": "Age doesn't matter"},
    {"text": "PewDiePie"},
    {"text": "Mark Zuckerburg"},
    {"text": "Creampie surprise"},
    {"text": "Wrong hole"},
    {"text": "A strip tease to the\nnational anthem"},
    {"text": "An attraction to men\nwith pedo-moustaches"},
    {"text": "COVID19"},
    {"text": "Shrek"},
    {"text": "A quest to lose your\nvirginity"},
    {"text": "Penis Envy"},
    {"text": "Going in debt for a\nuseless degree"},
    {"text": "A god complex"},
    {"text": "Surprise boners"},
    {"text": "Creating an onlyfans"},
    {"text": "Subbing to an onlyfans"},
    {"text": "Having a dad"},
    {"text": "A healthy relationship\nwith your dad"},
    {"text": "A foot fetish"},
    {"text": "A sad handjob"},
    {"text": "\"Surprise\" anal"},
    {"text": "Lying about being on the\npill"},
    {"text": "Trapping him with\npregnancy"},
    {"text": "Teen pregnancy"},
    {"text": "Depression"},
    {"text": "Schizophrenia"},
    {"text": "BPD"},
    {"text": "OCD"},
    {"text": "A cum fetish"},
    {"text": "A diet of semen"},
    {"text": "Bad Bitch Disease"},
    {"text": "Not washing your hands"},
    {"text": "A habit of groping\nstrangers"},
    {"text": "Rock hard titty implants\nand a pocket pussy"},
    {"text": "A dirty flesh light"},
    {"text": "14inch bad dragon dildo"},
    {"text": "9 inch dildo"},
    {"text": "Men"},
    {"text": "Women"},
    {"text": "Non-binarys"},
    {"text": "Depression meals"},
    {"text": "Waking up naked next to\nsix guys"},
    {"text": "Fully clothed female\nvideogame characters"},
    {"text": "Grave robbing"},
    {"text": "A phobia of erect\npenises"},
    {"text": "The biggest cum shot\never"},
    {"text": "Being reincarnated as a\ntampon"},
    {"text": "A full fursuit complete\nwith dick and balls"},
    {"text": "Lying to a girl to get\nher to put out"},
    {"text": "Falling for e-boys who\nwill never know you\nexist"},
    {"text": "Falling for e-girl who\nwill never know you\nexist"},
    {"text": "Asking to cum in her ear"},
    {"text": "An energy drink\naddiction"},
    {"text": "Chickie nugs not drugs"},
    {"text": "The pizza guy"},
    {"text": "Pussy decorating kits"},
    {"text": "\"you remind me of my\nmother\""},
    {"text": "\"you remind me of my\nfather\""},
    {"text": "An eating disorder"},
    {"text": "Black tits that produce\nchocolate milk"},
    {"text": "My Minecraft girlfriend"},
    {"text": "Freud"},
    {"text": "Jeffery Epstein"},
    {"text": "1312"},
/* Official Australia Deck */
    {"text": "Queen Elizabeth's\nimmaculate anus."},
    {"text": "Russell Crowe's shitty\nband."},
    {"text": "The big fucking hole in\nthe ozone layer."},
    {"text": "A marsupial that shits\ncubes."},
    {"text": "Copping a shag in the\nback of a ute."},
    {"text": "All four prongs of an\nechidna's penis."},
    {"text": "A didgeridildo."},
    {"text": "Harold Holt's bloated\ncorpse."},
    {"text": "Massive, widespread\ndrought."},
    {"text": "A six-point plan to stop\nthe boats."},
    {"text": "The entire cast of\nNeighbors."},
    {"text": "Tony Abbott in budgie\nsmugglers."},
    {"text": "9 out of 10 of the most\nvenomous snakes in the\nworld."},
    {"text": "The White Australia\nPolicy."},
    {"text": "Mooning the Queen."},
    {"text": "More sheep than people."},
    {"text": "Pingers."},
    {"text": "New Zealand's orc\nproblem."},
    {"text": "55 million cane toads."},
    {"text": "Contagious face cancer."},
    {"text": "A ute muster."},
    {"text": "Breaking the Silence."},
    {"text": "Bali belly."},
    {"text": "Dropping a baby down a\nthunderbox."},
    {"text": "A knife that's really a\nknife."},
    {"text": "Finding my mate Andy in\na blokes mag."},
    {"text": "Myxomatosis."},
    {"text": "A double plugger\nblowout."},
    {"text": "Total control of the\nmedia."},
    {"text": "Tasmanians."},
    {"text": "Kiwis."},
    {"text": "People smuggling."},
    {"text": "Slip-Slop-Slap."},
    {"text": "Steve Irwin."},
    {"text": "A meat raffle."},
    {"text": "Chundering into a\nkangaroo's pouch."},
    {"text": "Japanese whalers."},
    {"text": "Profound respect and\nappreciation for\nindigenous culture."},
    {"text": "A jolly swagman."},
    {"text": "The Stolen Generations."},
    {"text": "All kinds of skin\ncancer."},
    {"text": "The Bush."},
    {"text": "Clive Palmer opinions."},
    {"text": "A literal tornado of\nfire."},
    {"text": "Coon™ cheese."},
    {"text": "Skippy the Bush\nKangaroo."},
    {"text": "A suppository of wisdom."},
    {"text": "Sorry, this content\ncannot be viewed in your\nregion."},
    {"text": "Cashed-up bogans."},
    {"text": "Restoring the monarchy."},
    {"text": "A sensible gun control\npolicy."},
    {"text": "Rupert Murdoch."},
    {"text": "Seppos."},
    {"text": "Play-by-play commentary\nby Richie Benaud."},
    {"text": "Americanisation."},
    {"text": "The Great Emu War."},
    {"text": "Mr. Squiggle, the Man\nfrom the Moon."},
    {"text": "Quokka soccer."},
    {"text": "Good-natured, fun-loving\nAussie racism."},
    {"text": "Boat people: half boat,\nhalf human."},
    {"text": "Ned Kelly's helmet."},
    {"text": "Reading the future in\nRupert Murdoch's jowl\nfolds."},
    {"text": "Gina Rinehart."},
    {"text": "Making up for hundreds\nof years of oppression\nwith one day of\napologizing."},
    {"text": "Doing a Harold Holt."},
    {"text": "A fair go."},
    {"text": "Drinking Fosters\nironically."},
    {"text": "Getting glassed."},
    {"text": "A stingray barb through\nthe chest."},
    {"text": "A saliva-stained poster\nof Hugh Jackman."},
    {"text": "A five-litre goon bag."},
    {"text": "Guano."},
    {"text": "Sheep dags."},
    {"text": "The dingo that ate my\nbaby."},
    {"text": "Huggable loveable koalas\nwith chlamydia."},
    {"text": "Six months at the\nChristmas Island\nImmigration Detention\nCentre."},
    {"text": "Australia's next Chiko\nChick."},
    {"text": "A redback under the\ndunny seat."},
    {"text": "John Howard's eyebrows."},
    {"text": "ISnack 2.0."},
    {"text": "Moldy fairy bread."},
    {"text": "Boat people."},
    {"text": "Populate or perish."},
    {"text": "A sick burnout."},
    {"text": "Our first Koala Prime\nMinister."},
    {"text": "Playing sillybuggers."},
    {"text": "Having a Golden Gaytime."},
    {"text": "A four-by-four full of\ndead backpackers."},
    {"text": "˙ɐᴉlɐɹʇsnɐ."},
/* By Assholes, For Assholes Deck */
    {"text": "Sneezing while you take\na piss and the stream\ngoes everywhere."},
    {"text": "That awkward moment when\nyou realize your 3 way\nhas no vagina."},
    {"text": "When your balls are more\nblue than your wife's\neyes."},
    {"text": "YOUR MOM'S DICK!."},
    {"text": "A pile of sex."},
    {"text": "Unicorn semen."},
    {"text": "Purging the world of all\nthe furry porn."},
    {"text": "Passive aggressive ass\ntearing."},
    {"text": "Hitler's micropenis."},
    {"text": "Monica Lewinsky choking\non Bill Clinton's dick."},
    {"text": "Shitting in your\nneighbor's toilet and\nleaving the lid up."},
    {"text": "Two VERY lubricated\ngrandmothers fucking."},
    {"text": "Spongebob taking a dick\nin each hole."},
    {"text": "Getting a handjob from a\npirate."},
    {"text": "Having gay sex to go\nagainst authority."},
    {"text": "The elusive clitoris."},
    {"text": "A haughty rendition of \"\nLook At My Enormous\nPenis\"."},
    {"text": "Serial Anus Tickler."},
    {"text": "A metric fuckton of dead\nbabies."},
    {"text": "Using your girlfriend's\ncunt as an ashtray."},
    {"text": "Cocksucker."},
    {"text": "Fearlessly masturbating\nin your parents' room\nafter walking in while\nthey are having sex."},
    {"text": "Not changing your sheets\nfor 2 years and then\ntaking them off and\nwatching them stand up\nstraight."},
    {"text": "Using a sleeping hobo's\npenis as a fishing lure."},
    {"text": "Filming your parent's\nsex tape."},
    {"text": "Grandpa's collection of\nfurry porn."},
    {"text": "A sore ass in the\nmorning."},
    {"text": "Sleepwalking sex."},
    {"text": "Severe ass burgers."},
    {"text": "Having sloppy sex as\nyour dog watches."},
    {"text": "When a dick turns into a\nvagina during sex."},
    {"text": "Incest, for instance."},
    {"text": "Sticking a key in your\nlover's ass, turning it\nand yelling \"OPEN\nSESAME!\"."},
    {"text": "Ordering a five dollar\nfoot long. but getting a\ndick."},
    {"text": "Using your father as a\nbackup dildo."},
    {"text": "You little shits!."},
    {"text": "Slamming your laptop on\nyour dick to hide your\nporn and your dick."},
    {"text": "Sexual fantasies about\nNicolas Cage."},
    {"text": "You find that 9 month\nold jizz stain on the\nwall and think that you\ncould have had a baby."},
    {"text": "Finding a tick on your\ndick and making him\nexplode with the power\nof boners."},
    {"text": "Fucking Spiderman only\nto be webbed."},
    {"text": "Incestuous Catdog."},
    {"text": "Sucking a Slurpee harder\nthan you suck a dick."},
    {"text": "Drinking Pepsi after\nthey tell you it's Coke."},
    {"text": "People who show their\ndick on Omegle."},
    {"text": "Shit smeared on the wall\nin a public restroom."},
    {"text": "A Japanese contortionist\nfucking you in front and\nbehind at the same time."},
    {"text": "Using a vagina as a\npenis garage."},
    {"text": "A puddle of what may or\nmay not be smegma."},
    {"text": "Fucking the last known\nbison."},
    {"text": "Literally shitting\nnapalm."},
    {"text": "The muffled sounds of\nyour neighbors having\nvery rough sex through\nthe apartment wall."},
    {"text": "Sketchy places where you\ncan tell people have\nfucked."},
    {"text": "When you eat ass but not\navocados."},
    {"text": "A game of Twister that\ndegenerates into an\norgy."},
    {"text": "Watching porn on mute."},
    {"text": "A dick with a frown."},
    {"text": "Being peeked in on by a\nBrontosaurus while\nmasturbating."},
    {"text": "Masturbating with hand\nsanitizer."},
    {"text": "Masturbating to Anne\nFrank's diary."},
    {"text": "Effectively turning your\nanus into a confetti\ncannon."},
    {"text": "Masturbating\nresponsibly."},
    {"text": "Alien probes in your\nanus."},
    {"text": "Casually hiding your\nboner in your pantleg."},
    {"text": "Literally eating a dick."},
    {"text": "Emptying the cum\ndumpster."},
    {"text": "Getting AIDS and\nspreading it to as many\npeople as possible\nbefore your inevitable\ndeath."},
    {"text": "Finding an old condom in\nyour rectum."},
    {"text": "Michelle Obama getting\nfucked in a Snuggie by\nMitt Romney."},
    {"text": "One lonely testicle."},
    {"text": "A rhino horn up the ass."},
    {"text": "A porn star with daddy\nissues."},
    {"text": "Masturbating to a\npicture of your mother\nwhen she was 18 years\nold."},
    {"text": "Getting a rash from the\ndried cum on the inside\nof your favorite sock."},
    {"text": "A blowjob From Pingu\n(noot noot)."},
    {"text": "Using cum as coffee\ncreamer."},
    {"text": "Munching on corpses."},
    {"text": "Rubbing your dick on a\ncheese grater."},
    {"text": "A FUCKTON of furry porn."},
    {"text": "Cramming a rock hard\nthrobbing cock into a\ntight prepubescent ass."},
    {"text": "Teaching yoga to\namputees."},
    {"text": "Burying a cross deep in\nmy ass to feel Jesus\ninside me."},
    {"text": "Fingering Muhammad's\npenis hole."},
    {"text": "When you get semen stuck\nin your keyboard."},
    {"text": "Watching porn without\nheadphones to convince\nyour neighbors you are\nhaving sex."},
    {"text": "Using cum as mouthwash."},
    {"text": "Then all of a sudden, it\nstarted raining dildos."},
    {"text": "Swallowing the Kool-aid\nMan's cherry flavored\ncum."},
    {"text": "Cocksuckers who suck\nroosters instead of\npenises."},
    {"text": "Your dick stuck in a\ntoaster."},
    {"text": "Intercourse, turned\noutercourse, turned\ncrying."},
    {"text": "Superman and Lex Luther\nhaving to walk home\nafter a night of\nsuper-powered pelvic\nthrusting."},
    {"text": "An erotic sex scene\ninvolving Pikachu and a\nmuscular Bellsprout."},
    {"text": "Freeze dried orphans\nwith high quality\ngonads."},
    {"text": "Death by sperm."},
    {"text": "Accidentally inhaling\ncum."},
    {"text": "Your ferret excavating\nyour girlfriend's pussy."},
    {"text": "An 80ft tall inflatable\nChristmas tree that\nlooks suspiciously like\na buttplug."},
    {"text": "President Pussygrabber."},
    {"text": "Sitting back and\nwatching a blind man\nwalk off a cliff."},
    {"text": "More pussy than a cat\nshelter."},
    {"text": "When you freeze your\ndick to a pole during\nthe winter."},
    {"text": "Urethral fisting."},
    {"text": "Hitler, Stalin, the\nwhole crew."},
    {"text": "Mecha Hitler's COLOSSAL\nCOCK OF DOOM!!."},
    {"text": "Tits."},
    {"text": "When you see a shitty\nactor in an otherwise\ngreat movie."},
    {"text": "A rare species of fungus\nonly found in the smegma\nof Bulgarian goat\nherders.."},
    {"text": "Clubbing a baby seal\nwith your dick."},
    {"text": "A couple on the Titanic\ntrying to cum before\nthey drown."},
    {"text": "That patch of blue sky\nthrough the window\nbehind the large German\nman pummeling my anus."},
    {"text": "Sean Connery's ass."},
    {"text": "Ron getting very\n\"Weasley\" all up in\nHarry's young ass."},
    {"text": "Motherfucker."},
    {"text": "A dick thimble."},
    {"text": "Cunt."},
    {"text": "A vagina with teeth."},
    {"text": "Smegma?."},
    {"text": "Having anal sex with\nanother man, but saying\n\"no homo\" after."},
    {"text": "Genectically engineering\na two headed turtle for\nthe sole purpose of it\ngiving multiple\nblowjobs."},
    {"text": "A dick in a box."},
    {"text": "Preforming a sex move\ncalled \"The\nTriceratops\"."},
    {"text": "Calling your dick \"The\nRevered Woodsworth\"."},
    {"text": "Kim Jong Un's stupid\nfucking haircut."},
    {"text": "Being a Jedi and using\nyour lightsaber as a\ndildo."},
    {"text": "An inconspicuous dick\njoke."},
    {"text": "Using your phone as a\nvibrator."},
    {"text": "Piss."},
    {"text": "An old timey film of my\ngrandmother's first\ngangbang."},
    {"text": "Shit."},
    {"text": "Fuck."},
    {"text": "That one fucking dead\npixel in the middle of\nthe screen."},
    {"text": "Sucking on a vape harder\nthan your boyfriend's\ncock."},
    {"text": "Tentacle porn with\nactual real life\njellyfish."},
    {"text": "An African tribal sex\nritual."},
    {"text": "Firing toothpicks out of\none's penis."},
    {"text": "A stripper with polio."},
    {"text": "A deranged sociopath\nhell bent on being\nHitler 2.0."},
    {"text": "Fucked Donald Trump so\nhard he said I \"Trumped\"\nhim."},
    {"text": "Giving a man a boner\nthen cutting it to bleed\nhim out."},
    {"text": "Sharing a sexy bath and\nthen eating the soap."},
    {"text": "Downloading 4K porn when\nyou have a 720p monitor."},
    {"text": "A cheap dildo that\nbreaks after one use."},
    {"text": "Fat Bastard from Austin\nPowers."},
    {"text": "Scrubbing the shit out\nof my daughter's dick."},
    {"text": "Filing a lawsuit on a\ndolphin for sexual\nharassment."},
    {"text": "Fucking your pillow only\nfor it to get pregnant."},
    {"text": "Slurping spaghetti out\nyour partner's asshole."},
    {"text": "A midget too short to\nget his dick through the\ngloryhole."},
    {"text": "Using a spork to scoop\nout a homeless man's\neyeballs."},
    {"text": "Bagel Chasers."},
    {"text": "Going to Arby's and\ngetting the \"Meat\nMountain\"."},
    {"text": "A blow job so good it\ncauses you to transcend\nspace-time and enter\ninto the metaphysical\nrealm."},
    {"text": "King Kong pleasuring\nhimself with the Empire\nState Building."},
    {"text": "Helen Keller performing\na circumcision."},
    {"text": "Heteroerotic clowns."},
    {"text": "Understanding Chinese\naccents when you order\nover the phone."},
    {"text": "Dead babies."},
    {"text": "An unnecessary amount of\ndrugs."},
    {"text": "The War Of Northern\nAggression."},
    {"text": "Harvey Weinstein."},
    {"text": "A hairy man riding a\nhairless yak."},
    {"text": "Grabbing her cheeks and\nramming her hard."},
    {"text": "Using a Snicker's\nwrapper as a condom."},
    {"text": "Secondhand adult\ndiapers."},
    {"text": "A felony in all 50\nstates."},
    {"text": "An entire town giving\nGodzilla a lapdance."},
    {"text": "A little bird cumming in\na hippo's mouth."},
    {"text": "Drowning in female\ngenitalia."},
    {"text": "Swiggity swooty, I'm\ncoming for that booty."},
    {"text": "Pleasurably inserting a\ncable into one's\nurethra."},
    {"text": "Gourmet cannibalism."},
    {"text": "A blind guy attempting\nto pick up chicks."},
    {"text": "Feeding your newborn\nbaby birth control to\ntry to undo the birth."},
    {"text": "Nuns with nice buns."},
    {"text": "Frostbitten genitals."},
    {"text": "98 year old cougars."},
    {"text": "Copious amounts of\nheroin."},
    {"text": "M. KNIGHT\nSHAMAMALLAMASAMA..."},
    {"text": "Second hand lube."},
    {"text": "Orphans genetically\nengineered to explode\nwhen loved."},
    {"text": "Taking your extra\nclothes hangers to the\nabortion clinic."},
    {"text": "Every type of cancer."},
    {"text": "Finding a condom in your\ndaughter's backpack."},
    {"text": "Abradolph Lincler."},
    {"text": "Vaguely racist old\npeople comments."},
    {"text": "Hormonally enraged\ntoddlers."},
    {"text": "The Church of Latter Day\nTaints."},
    {"text": "Wolverine giving himself\na vasectomy."},
    {"text": "Cumming on the floor and\nblaming it  on Grandma."},
    {"text": "Volunteering to give\nhandjobs to the severely\ndisabled."},
    {"text": "Glancing at the\nWashington monument and\nchuckling \"Mine's\nbigger.\"."},
    {"text": "The cast of Sesame\nStreet killing and\neating Big Bird."},
    {"text": "Tree trunk abortions."},
    {"text": "Selling your baby during\nBlack Friday."},
    {"text": "Bob Ross brutally\nmurdering his family\nwith a paintbrush."},
    {"text": "Jared From Subway\nshowing kids his 5\nDollar Foot Long."},
    {"text": "Going into maximum\noverdrive."},
    {"text": "Old white men in blue\njeans."},
    {"text": "Snorting coke and\nrealizing too late that\nit's actually heroin."},
    {"text": "A bottle of orphan\ntears."},
    {"text": "Stevie Wonder on a\ntrampoline."},
    {"text": "A midget with his 3rd\nleg so long he can't\nstand up straight."},
    {"text": "A sea lion engaged in a\nknife fight with a\nregular lion."},
    {"text": "Using a Jigglypuff as a\ncondom."},
    {"text": "The closed redneck gene\npool."},
    {"text": "Making eye contact with\na stranger while eating\na banana."},
    {"text": "Jacking off to Fifty\nShades of Grey: The\nMovie while you're in\nthe theater."},
    {"text": "Nipple lasers."},
    {"text": "Human skin carpets."},
    {"text": "The lightning speed\nevery teenage boy\nachieves when he's\nfapping and his door\nopens."},
    {"text": "A Moray eel deciding to\nlive in your bumhole."},
    {"text": "Using a drinking straw\nas a catheter."},
    {"text": "Swapping a man's\ntesticles with his\neyeballs."},
    {"text": "Grandpa using grandma's\nurn of ashes as a\nFleshlight."},
    {"text": "Pelvic thrusting across\nthe deep blue sea."},
    {"text": "Just a little bit of\ngay."},
    {"text": "Plan B."},
    {"text": "Throwing a shot put into\na crowd and making it\nlook like an accident."},
    {"text": "Jacking it in San Diego."},
    {"text": "Fine, aged, European\nfromunda cheese."},
    {"text": "The Alaskan pancake pile\ndriver upside down milk\nmachine."},
    {"text": "Breast suffocation."},
    {"text": "Walking into a Jewish\nneighborhood and\ndropping a penny."},
    {"text": "A sock and my right\nhand."},
    {"text": "Loving your mom a little\ntooooo much."},
    {"text": "Taking one look at your\nnew baby then shoving it\nback in."},
    {"text": "Alcohol-fueled\nThanksgiving Day family\nfist fights."},
    {"text": "A hippo cumming in a\nlittle bird's mouth."},
    {"text": "Flex Seal ®."},
    {"text": "Ronald McDonald's Secret\nSauce."},
    {"text": "CHARIZARDING!!!."},
    {"text": "Practicing your\nventriloquism at a\nfuneral."},
    {"text": "Putting out at Church."},
    {"text": "Skinny dipping in Russia\nand dying."},
    {"text": "Picking up dates in the\nball pit at Chuck E.\nCheese."},
    {"text": "Setting fat kids on fire\nto burn calories."},
    {"text": "Fingering the pope."},
    {"text": "A monster condom for my\nmagnum dong."},
    {"text": "ALL OF THE STDS!."},
    {"text": "A rim job from a heavily\nbearded man."},
    {"text": "Jacking off in your\nparents' bed as a form\nof revenge."},
    {"text": "Having a literal\nskeleton in your closet."},
    {"text": "Mistaking your roofies\nfor allergy pills."},
    {"text": "How white people smile\nat Black people."},
    {"text": "Dorothy using the\nscarecrow as firewood."},
    {"text": "An Alabama hot pocket."},
    {"text": "Drowning in male\ngenitalia."},
    {"text": "Posting babies on\nCraigslist."},
    {"text": "A bigger, better, Soviet\nUnion."},
    {"text": "Large scale baby juicing\noperation, producing the\nbest baby juice this\nside of the Mississippi."},
    {"text": "A Black guy in a white\nneighborhood."},
    {"text": "Feeding starving orphans\ntheir own parents."},
    {"text": "Beating little kids at\nPokemon until they cry."},
    {"text": "The Whomping  Willow\nWhomping Hagred."},
    {"text": "Buttchugging."},
    {"text": "Sword swallowers who\nswallow dicks instead of\nswords."},
    {"text": "Ebenezer Scrooge showing\nTiny Tim his \"ghost of\nChristmas present\"."},
    {"text": "The moose from last\nnight."},
    {"text": "That Flex Tape guy\nsawing the Titanic in\nhalf."},
    {"text": "A poopstick."},
    {"text": "Taking a man sized dump\nin your friend's catbox\nto make him think his\ncat is seriously ill."},
    {"text": "Deepthroating a\ncucumber."},
    {"text": "Louis C.K., notable\ncomedian and\nmasturbator."},
    {"text": "Lemon scented lube."},
    {"text": "Two garden gnomes doing\nit in your yard."},
    {"text": "Pushing a double amputee\ndown a flight of stairs."},
    {"text": "Her Royal Highness'\nmatched luggage."},
    {"text": "Getting head on a\nsubway."},
    {"text": "Stephen Hawking working\nthe pole."},
    {"text": "Seducing a monk by\nputting on more clothes."},
    {"text": "Thoughts and prayers."},
    {"text": "Chewbacca and Han Solo's\nbasement baby."},
    {"text": "Challenging a bear for\nhis honey."},
    {"text": "Serving a BBQ dinner at\nthe hospital burn ward."},
    {"text": "A wild boar reaming Matt\nDamon."},
    {"text": "Using mayonnaise as\nlube, only to attract\nants."},
    {"text": "Winnie the Pooh using a\nhoney pot to asphyxiate\nhimself."},
    {"text": "Pope orgies."},
    {"text": "A black baby painted\nwhite with love juice."},
    {"text": "Making seagulls die by\nfeeding them\nAlka-Seltzer."},
    {"text": "Black market flu shots."},
    {"text": "Getting dumped by your\nleft hand."},
    {"text": "A singular dead baby."},
    {"text": "EbolAIDS."},
    {"text": "The Bombings of\nHiroshima and Nagasaki."},
    {"text": "Marking a prostitute as\nyour territory."},
    {"text": "The very idea that more\nthan two genders exist."},
    {"text": "Mormonism."},
    {"text": "A Bear riding an actual\nbear."},
    {"text": "One heaping tablespoon\nof Ebola."},
    {"text": "An angel with wings made\nof fried chicken."},
    {"text": "Using chopsticks to eat\nyour neighbor alive."},
    {"text": "Being gay to please the\nLiberals."},
    {"text": "Drinking hand sanitizer\nto cure your cold."},
    {"text": "The prefect equilibrium\nof a elderly man\neternally falling down\nan ascending escalator."},
    {"text": "Finding a starving\norphan on the street and\nputting them out of\ntheir misery."},
    {"text": "Post-birth abortion."},
    {"text": "9/11 jumpers."},
    {"text": "Plowing a hoe on a plow\nwith a hoe."},
    {"text": "Spelling dirty words\nwhile playing Scrabble\nwith your kids."},
    {"text": "At least three bears."},
    {"text": "Opening the Harvard\nCollege of Hookers."},
    {"text": "Stoning the blind man\nbecause he'll never see\nit coming."},
    {"text": "Fully clothed hookers\nfrom the 1700's."},
    {"text": "Freezing Vapor Rub,\ncrushing it and snorting\nit."},
    {"text": "Widening your urethra\nwith a taffy puller."},
    {"text": "Urban Dictionary's Word\nOf The Day."},
    {"text": "A good ol' fashioned\ngame of \"Is It Racist?\"."},
    {"text": "The Tin Man dismembering\nthe Wicked Witch with a\nhatchet."},
    {"text": "Mouth chlamydia."},
    {"text": "Waluigi's uncircumcised\nWaluweewee."},
    {"text": "Jerking off into the\nshampoo bottle and\nputting it back in the\nshower to save money on\nshampoo."},
    {"text": "Initiating a foursome\nwith the Three Stooges."},
    {"text": "Mr. Potato Head being\nserved in a Happy Meal."},
    {"text": "Snuffleupagus with a\ncoke problem."},
    {"text": "Losing your virginity to\na Nerf football."},
    {"text": "Blowing a load into an\nelephant's trunk."},
    {"text": "Autoerotic asphyxiation."},
    {"text": "A silverback gorilla\neyeing you from across\nthe zoo."},
    {"text": "Rubbing your genitals\ntogether to generate\nelectricity."},
    {"text": "Wet dreams so explosive\nyou drown."},
    {"text": "Thumping up the wrong\nrabbit hole."},
    {"text": "🍆 💦."},
    {"text": "Commiting genocide with\nnothing but your good\nlooks and a railroad\nspike."},
    {"text": "A small bloodstain on\nthe bedsheet."},
    {"text": "Obama and Romney both\ntaking a heaping helping\nof Clinton's member."},
    {"text": "Snorting the Ramen spice\npack."},
    {"text": "Forgetting to clear your\nbrowser history."},
    {"text": "Being penetrated by a\nbaseball bat wrapped in\nbarbed wire."},
    {"text": "A starfish giving five\nhandjobs at the same\ntime."},
    {"text": "That obese naked man\nfapping in the corner."},
    {"text": "Making friends with that\none weird white kid...\njust in case."}
  ]
}